# numpy is array processing package, used inscientific calculations, has c++ bindings

In [1]:
a=[1,2,3,4,5,6]


In [2]:
import numpy as np


In [19]:
arr=np.array(a)

In [20]:
arr.shape

(6,)

In [21]:
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
a=[1,2,3,4,5,6]
b=[1,2,3,4,5,6]
c=[1,2,3,4,5,6]
arr1=np.array([a,b,c])

In [17]:
arr1

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [22]:
type(arr1)

numpy.ndarray

In [24]:
arr1.shape

(3, 6)

In [33]:
arr2=arr1.reshape(6,3)

In [30]:
arr1

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [34]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# indexing starts from 0

In [27]:
arr[3]

4

In [31]:
arr1[1:,3:]

array([[4, 5, 6],
       [4, 5, 6]])

In [45]:
arr2[1:3,2:]

array([[6],
       [3]])

In [54]:
arr4=np.arange(100,200,10)

In [55]:
arr4

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [59]:
arr4[3:]

array([130, 140, 150, 160, 170, 180, 190])

In [60]:
np.linspace(2,10,50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [61]:
np.linspace(2,10,50,retstep=True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 0.16326530612244897)

# broad masking and copy

In [69]:
arr5=arr

In [72]:
arr5[3:]=300

In [73]:
arr5

array([  1,   2,   3, 300, 300, 300])

In [74]:
arr

array([  1,   2,   3, 300, 300, 300])

In [78]:
arr6=arr.copy()

In [79]:
arr6[3:]=1000

In [80]:
arr6

array([   1,    2,    3, 1000, 1000, 1000])

In [81]:
arr

array([  1,   2,   3, 300, 300, 300])

# EDA Useful tips

In [82]:
arr[arr<3]

array([1, 2])

arr.reshape

In [83]:
arr5*arr

array([    1,     4,     9, 90000, 90000, 90000])

In [84]:
np.ones(4)

array([1., 1., 1., 1.])

In [85]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
np.random.rand(3,3)

array([[0.41475203, 0.81145461, 0.37493607],
       [0.03461685, 0.4692751 , 0.1566211 ],
       [0.94956168, 0.46462909, 0.53335053]])

# np.random.randn(4,4) using standard normal distribution

In [88]:
np.random.randn(4,4)

array([[ 1.32028072,  0.09156672, -1.90049839,  1.08577991],
       [ 0.95739875, -0.52213499, -0.27936331,  2.48639649],
       [ 0.56300499, -0.46315847,  0.03113793,  0.6948643 ],
       [ 1.2021956 ,  0.25848073,  0.60733812,  1.30037688]])

In [94]:
np.random.randint(4,100,8)

array([25, 75, 51, 79, 91, 88, 18, 15])

In [98]:
np.random.random_sample((2,5))

array([[0.46380744, 0.77667598, 0.38353361, 0.26892197, 0.96419022],
       [0.56711305, 0.61474037, 0.2553301 , 0.08222824, 0.73242419]])